name: Release Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm
    if: github.event.release.draft == false && github.event.release.prerelease == false || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify tag matches package version
        if: github.event_name == 'release'
        run: |
          TAG="${{ github.event.release.tag_name }}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG" != "v$PKG_VERSION" ]; then
            echo "Release tag $TAG does not match package version $PKG_VERSION"
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Test
        run: npm test -- --ci

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: |
          ORIGINAL_NAME=$(node -p "require('./package.json').name")
          OWNER_SCOPE=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          SCOPED_NAME="@${OWNER_SCOPE}/startgg-oauth2-full"
          npm pkg set name="$SCOPED_NAME"
          npm publish --registry https://npm.pkg.github.com
          npm pkg set name="$ORIGINAL_NAME"
